[tox]
basepython = python3.12
envlist =py3{12}-ansible{220,217}
skipsdist = true

[testenv]
passenv = *
setenv =
    CLICKHOUSE_USER = admin
    CLICKHOUSE_PASSWORD = admin
deps =
    -r tox-requirements.txt
    ansible220: ansible-core<2.20.5
    ansible217: ansible-core<2.17.0
commands =
    {posargs:molecule test -s default --destroy always}