---
# Purpose: bring the instance to the desired state by running the role under test.
# Molecule calls this playbook with `molecule converge`.
- name: Converge
  hosts: vector
  gather_facts: true  # Disable if your role does not rely on facts
  tasks:
    - name: Show service manager
      ansible.builtin.debug:
        var: ansible_facts['service_mgr']

    - name: Apply role under test
      ansible.builtin.include_role:
        name: vector
