---
# Dependency management (download roles/collections)
dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml
platforms:
  - name: molecule-netology
    image: rockylinux:9
  - name: molecule-oracle
    image: oraclelinux:9
  - name: molecule-ubuntu
    image: ubuntu:latest

ansible:
  cfg:
    defaults:
      roles_path: /home/dops/Yandex.Disk/repo/dops-hw/ansible/hw-ansi-04/roles/
      host_key_checking: false
      verbosity: 1
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_FORCE_COLOR: "1"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "1"

  executor:
    backend: ansible-playbook
    args:
      ansible_navigator:
        - --mode stdout
        - --pull-policy missing
        - --execution-environment-image ghcr.io/ansible/community-ansible-dev-tools:latest

  playbooks:
    create: create.yml
    converge: converge.yml
    destroy: destroy.yml
    cleanup: cleanup.yml
    prepare: prepare.yml
    verify: verify.yml

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - idempotence
    - cleanup
    - destroy
